// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/logos/CleanElevated.tsx": () => import("../components/mockups/logos/CleanElevated.tsx"),
  "./components/mockups/logos/MetallicGold.tsx": () => import("../components/mockups/logos/MetallicGold.tsx"),
  "./components/mockups/logos/PremiumDark.tsx": () => import("../components/mockups/logos/PremiumDark.tsx"),
  "./components/mockups/logos/RoyalDeep.tsx": () => import("../components/mockups/logos/RoyalDeep.tsx")
};
