uploads = []

[[generated]]
id = "0JyGk6uGyGeu0_RWhzzd-"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "fanni-app-icon"

[[generated]]
id = "qx7lmtT6AeBqp-izaiDui"
uri = "file://artifacts/mobile/assets/images/splash.png"
type = "image"
title = "fanni splash background"

[[generated]]
id = "Sy90HVJn4NfwIuV2tcf9i"
uri = "file://artifacts/mobile/assets/images/categories_bg.png"
type = "image"
title = "fanni categories banner"

[[generated]]
id = "XCeC5XBQ_l7mAAmMFU6az"
uri = "file://artifacts/mobile/assets/images/splash-icon.png"
type = "image"
title = "fanni-splash"

[[outputs]]
id = "4Gs2IWV17ltcuUknQ572v"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "شعار فني — أيقونة التطبيق (Welcome Screen)"

[[outputs]]
id = "G1ZTwlfJpLhesnCRpjNQy"
uri = "file://artifacts/mobile/assets/images/splash-icon.png"
type = "image"
title = "شعار فني — صفحة البداية (Splash Screen)"
