# =============================================================================
# Export PRODUCTION env template for Git (VPS pulls from Git).
# Reads:  .env.production (local, gitignored) OR .env.production.example
# Writes: deploy/env.production.example  (safe — secrets redacted)
# Usage:  powershell -ExecutionPolicy Bypass -File scripts\export-prod-env-for-git.ps1
#         pnpm run env:export-prod
# =============================================================================
param(
  [switch]$ForceFromExample
)

$ErrorActionPreference = "Stop"
$Root = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot ".."))
Set-Location -LiteralPath $Root

$src = Join-Path $Root ".env.production"
if ($ForceFromExample -or -not (Test-Path -LiteralPath $src)) {
  $src = Join-Path $Root ".env.production.example"
}
if (-not (Test-Path -LiteralPath $src)) {
  throw "Missing .env.production and .env.production.example"
}

$secretKeys = @(
  "DATABASE_URL",
  "SESSION_SECRET",
  "SMTP_PASS",
  "SMS_API_KEY",
  "SMS_API_SECRET",
  "TWILIO_AUTH_TOKEN",
  "TWILIO_ACCOUNT_SID",
  "OIDC_CLIENT_SECRET",
  "LT_ACCESS_KEY",
  "OPENAI_API_KEY",
  "TOMTOM_API_KEY"
)

# Public / non-secret keys allowed in Git as concrete values
$allowConcrete = @(
  "NODE_ENV",
  "PORT",
  "LOG_LEVEL",
  "PUBLIC_API_URL",
  "CORS_ORIGINS",
  "DISPUTE_AUTO_DAILY_CAP",
  "PAYMENT_PROVIDER",
  "STORAGE_DRIVER",
  "PRIVATE_OBJECT_DIR",
  "PRIVATE_OBJECT_DIR_ID",
  "PRIVATE_OBJECT_DIR_CARNEHAT",
  "EXPO_PUBLIC_API_URL",
  "EXPO_PUBLIC_DOMAIN",
  "EXPO_PUBLIC_REPL_ID",
  "EXPO_PUBLIC_SENTRY_DSN",
  "SENTRY_DSN",
  "SENTRY_RELEASE",
  "SENTRY_ENVIRONMENT",
  "ENABLE_OTP"
)

$lines = Get-Content -LiteralPath $src
$out = New-Object System.Collections.Generic.List[string]
$out.Add("# Auto-exported for Git / VPS bootstrap — DO NOT put real passwords here.")
$out.Add("# Generated by: pnpm run env:export-prod")
$out.Add("# Source: $(Split-Path -Leaf $src)  ($(Get-Date -Format 'yyyy-MM-dd HH:mm'))")
$out.Add("# VPS: copy to /var/www/fanni/.env and fill DATABASE_URL + SESSION_SECRET.")
$out.Add("# Apache + PM2 listen on 127.0.0.1:5000. Public URL: https://api.upnexa-eg.com")
$out.Add("")

foreach ($raw in $lines) {
  $line = $raw.TrimEnd()
  if ($line -eq "" -or $line.StartsWith("#")) {
    # skip old header comments; keep blank structure lightly
    continue
  }
  $eq = $line.IndexOf("=")
  if ($eq -lt 1) { continue }
  $key = $line.Substring(0, $eq).Trim()
  $val = $line.Substring($eq + 1).Trim()
  if (($val.StartsWith('"') -and $val.EndsWith('"')) -or ($val.StartsWith("'") -and $val.EndsWith("'"))) {
    $val = $val.Substring(1, $val.Length - 2)
  }

  if ($secretKeys -contains $key) {
    $out.Add("# $key=  # set on VPS only — never commit")
    continue
  }

  if ($allowConcrete -contains $key) {
    if ([string]::IsNullOrWhiteSpace($val)) {
      $out.Add("# $key=")
    } else {
      $out.Add("$key=$val")
    }
    continue
  }

  # Unknown keys: comment as placeholder
  $out.Add("# $key=")
}

$dest = Join-Path $Root "deploy\env.production.example"
$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllLines($dest, $out.ToArray(), $utf8NoBom)

Write-Host "[env:export-prod] wrote $dest" -ForegroundColor Green
Write-Host "  Secrets redacted: $($secretKeys -join ', ')"
Write-Host "  Next: git add deploy/env.production.example && commit/push"
Write-Host "  VPS still uses its own .env; template is for bootstrap/docs only."
